### ISSUE TITLE
Can overlay run in SteamVR Home or steam game?

### ISSUE THREAD

**Issue by TitansWhale** [mbucchia/OpenXR-Layer-Template#3]
Thank you for your tutorial.
I have tested the "**Tutorial 2: Your first in VR overlay**" project and it runs successfully in **Hello XR**. However, when I open **SteamVR Home** or **VRChat** on the Steam platform, the overlay is not displayed. I'm not sure why this is happening.
![image](https://github.com/mbucchia/OpenXR-Layer-Template/assets/26743177/2c0bd5cc-f3da-41d7-97b5-44816040f0d8)

![image](https://github.com/mbucchia/OpenXR-Layer-Template/assets/26743177/dada10ef-facd-44b2-a3d5-d88749cab905)

**Comment by mbucchia** [comment]
Hmm neither SteamVR home nor VR Chat use OpenXR. 

This project is an OpenXR API layer for OpenXR applications. It will only work with an OpenXR application running.

**Comment by mbucchia** [comment]
If you are looking for something that runs into SteamVR regardless of the app (OpenVR or OpenXR), look at `IVROverlay`. But using that solution will not work for users that don't use SteamVR (eg: OpenXR via native platform support). Hence the existence of this tutorial.

**Comment by TitansWhale** [comment]
> 

Thank you for your advice. Your suggestion has been very helpful to me.
