### ISSUE TITLE
xrSyncActions causes problems

### ISSUE THREAD

**Issue by sergioberg** [mbucchia/OpenXR-Layer-Template#4]
Everything I talk about below is related to the Oculus OpenXR runtime.

I noticed that “priority” from “XrActionSetCreateInfo” does not work at all, it has absolutely no effect when using this runtime. This can be easily seen in the game Beat Saber, but more on that game later.

I made an overlay that attaches to the hand. And here's what I noticed:
Calling "xrSyncActions" from "xrBeginFrame_subst" doesn't seem to be a good idea. For example, the game - Population One - has an overlay where it is needed, but the hands in the game lie on the floor and do not move at all, only the poses of fingers change when the controller buttons are pressed.
I moved the "xrSyncActions" call to "xrEndFrame" and this completely solved the problems in Population One.
But even this doesn’t help with the game Beat Saber. In it, on individual frames, the overlay is reset to the zero position of the “Local” space(No matter where call "xrSyncActions"). And the “swords” in the game end up on the ground in these frames. Changing the priority doesn't change anything.

I just wanted to bring information to you. Close this issue whenever you see fit. 
Thank you for this Templates.

**Comment by BuzzteeBear** [comment]
I think the issue of calling xrSyncAction with your own actionset is that the original actionsets of the game are left inactive until the next regular call of xrSyncAction. 

Did you already try to intercept the xrSyncAction call instead of doing your own and just adding your actionset in the process?
Like this: https://github.com/BuzzteeBear/OpenXR-MotionCompensation/blob/bdd3d885c3b3cb04eb7ad2ffc48b85e25949826d/XR_APILAYER_NOVENDOR_motion_compensation/layer.cpp#L874

Just my 5 cents...

**Comment by mbucchia** [comment]
I have a fix for this (which is similar to what @BuzzteeBear suggested above), I just haven't merged it yet to the public repository.

**Comment by sergioberg** [comment]
> Did you already try to intercept the xrSyncAction call instead of doing your own and just adding your actionset in the process? Like this: https://github.com/BuzzteeBear/OpenXR-MotionCompensation/blob/bdd3d885c3b3cb04eb7ad2ffc48b85e25949826d/XR_APILAYER_NOVENDOR_motion_compensation/layer.cpp#L874

Thanks, I'm trying. For some reason my ActionSet is not updated at all in that variant. I'm trying to figure out what I'm doing wrong.

**Comment by sergioberg** [comment]
Started everything from scratch. And I fixed everything, everything works. Thank you!
